using System;
using System.Net;
using System.Threading.Tasks;
using Convoy.ErrorHandling;
using Npgsql;

namespace ConsiliaAPI.Objects
{
    public class User
    {
        /// <summary>
        /// Secure Sign On Key. Random nonce generated by user to be used like a password.
        /// </summary>
        public string SSOKey { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ProfilePic { get; set; }
        public Guid UserUUID { get; set; }

        public static async Task<User> CreateUser(string fname, string lname, string ssoKey)
        {
            try
            {
                User u = new User();
                // Generate User's details
                u.SSOKey = ssoKey;
                u.FirstName = fname;
                u.LastName = lname;
                u.UserUUID = Guid.NewGuid();

                // Insert them into database
                NpgsqlConnection conn = Database.DatabaseConnection;
                NpgsqlCommand command =
                    new NpgsqlCommand(
                        $"INSERT INTO USERS(user_uuid, first_name, last_name, sso_key) " +
                        $"VALUES(\'{u.UserUUID}\', \'{u.FirstName}\', \'{u.LastName}\', \'{u.SSOKey}\')", conn);
                await command.ExecuteNonQueryAsync();

                return u;
            }
            catch (Exception e)
            {
                throw new ConvoyException("Unable to create user.", HttpStatusCode.InternalServerError, e.StackTrace);
            }
        }
    }
}